### ISSUE TITLE
Bug with PHP 7.1

### ISSUE THREAD

**Issue by imkane** [rainlab/forum-plugin#108] opened 2017-06-06 15:52 UTC
On the main Forum page (https://yardyum.com/forum), the Recent Topic links weren't redirecting properly. (We've since patched the bug by forcing the page URL var to always = 0 so you can't recreate this on our site anymore).

For example:
https://yardyum.com/forum/topic/hey-fellow-yummers?page=last#post-27
Isn't redirecting to:
https://yardyum.com/forum/topic/hey-fellow-yummers?page=1#post-27

So we get:
production.ERROR: ErrorException: A non-numeric value encountered in /var/www/yardyum.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1262

It seems like this is happening:
https://stackoverflow.com/questions/42044127/warning-a-non-numeric-value-encountered

**Comment by LukeTowers** [comment] 2017-10-26 23:21
Duplicate of #103

**Closed by LukeTowers** 2017-10-26 23:21 UTC
