### ISSUE TITLE
Forum / Blog Reply Exception

### ISSUE THREAD

**Issue by nitin19srivastava** [rainlab/forum-plugin#111] opened 2017-09-01 11:01 UTC
![capture](https://user-images.githubusercontent.com/25565327/29967178-009265b6-8f33-11e7-9001-359d89c85125.PNG)

How to solve this error.?

**Comment by LukeTowers** [comment] 2017-10-26 23:22
Duplicate of #103

**Closed by LukeTowers** 2017-10-26 23:22 UTC
